### ISSUE TITLE
Fails in IE11

### ISSUE THREAD

**Issue by mtimms** [gooy/aurelia-animator-velocity#1]
Works in Chrome and Firefox, but appears to have a problem in IE11.
HTML1300: Navigation occurred. File: aurelia-animator-velocity Unhandled promise rejection Error loading "github:aurelia/html-template-element@0.2.0" at http://gooy.github.io/aurelia-animator-velocity/jspm_packages/github/aurelia/html-template-element@0.2.0.js Not Found: http://gooy.github.io/aurelia-animator-velocity/jspm_packages/github/aurelia/html-template-element@0.2.0.js

**Comment by Aaike** [comment]
Hi @mtimms thx for testing it.

I have fixed the issue where the html-template-element file was missing.
But now an issue remains, Aurelia does not seem to trigger page animatons in IE11.

I have openend in issue for this here : https://github.com/aurelia/templating/issues/86

**Comment by mtimms** [comment]
Thanks, @Aaike I'll keep a watch out for this fix.  Liking what I've seen of this so far in the other browsers. :)

**Comment by Aaike** [comment]
can be tracked here: https://github.com/gooy/aurelia-animator-velocity/issues/3
