### ISSUE TITLE
Use event aggregation to provide animation events

### ISSUE THREAD

**Issue by zewa666** [gooy/aurelia-animator-velocity#4]
Same as for issue https://github.com/aurelia/animator-css/issues/13 for the CssAnimator, we should call the mentioned DOM-Events. In case of JS based events, the timeout events won't be necessary. I guess same applies for staggering animations

animation:enter:begin
animation:enter:active
animation:enter:done
~~animation:enter:timeout~~

---

animation:leave:begin
animation:leave:active
animation:leave:done
~~animation:leave:timeout~~

---

~~animation:stagger:next~~

---

animation:remove-class:begin
animation:remove-class:done
~~animation:remove-class:timeout~~

---

animation:add-class:begin
animation:add-class:done
~~animation:add-class:timeout~~

**Comment by Aaike** [comment]
these have been implemented now :)
