### ISSUE TITLE
jspm install not working

### ISSUE THREAD

**Issue by cehoffman** [gooy/aurelia-animator-velocity#5]
The instructions for installation say to install using `jspm install gooy/aurelia-animator-velocity` but this doesn't work. Modifying this to `jspm install github:gooy/aurelia-animator-velocity` fixes this but then jspm complains about a missing `main` in configuration which causes the import statement in code to fail.

**Comment by Aaike** [comment]
i was in the process of updaing this package ;)

please not that this package will be moved soon to an aurelia repository and this one will be deleted.

**Comment by cehoffman** [comment]
I hope to see the changes soon then.

The other issue I have, which I'm unsure if this is jspm, is that once installed using your now update 0.0.3 tag the require statement for aurelia-templating, jsol, and velocity all fail to resolve. aurelia-templating I can understand since it isn't a direct dependency, but jsol and velocity are so shouldn't jspm be resolving those relative to the mapping in config.js.

**Comment by Aaike** [comment]
yes it should.
the templating repo should have been defined as a dependency in the package.json as well.
i will be cleaning it up in the coming few days
