### ISSUE TITLE
installation instructions don't work

### ISSUE THREAD

**Issue by dkent600** [gooy/aurelia-animator-velocity#8]
The installation instructions state to install the package using the following command:

`jspm install gooy/aurelia-animator-velocity`

However, running the command results only in the following error message:

"err  Repo jspm:gooy/aurelia-animator-velocity not found."

**Comment by Narven** [comment]
@dkent600 if you have aurelia-cli with the latest version use:

`au install aurelia-animator-velocity`

**Comment by Narven** [comment]
You will need also `velocity-animate` package.

Also there is a problem with the velocity-animate package, because aurelia-animator-velocity is calling for a velocity.js package that does not exists.

Add this to you aurelia.json:

```
{
            "name": "aurelia-animator-velocity",
            "main": "aurelia-animator-velocity",
            "path": "../node_modules/aurelia-animator-velocity/dist/amd",
            "resources": [],
            "deps": ["velocity-animate"]
          },
          {
            "name": "velocity-animate",
            "path": "../node_modules/velocity-animate",
            "main": "velocity",
            "deps": ["jquery"],
            "resources": ["velocity.ui.js"]
          },
          {
            "name": "velocity",
            "path": "../scripts/velocity-shim"
          }
```

and add this script to scripts folders `velocity-shim.js`:

```
define('velocity', ['velocity-animate'], function(velocity) {
  return velocity;
});
```

**Comment by Aaike** [comment]
please use the official aurelia-animator-velocity package : https://github.com/aurelia/animator-velocity

sorry for the confusion , i will remove this repo soon
